### ISSUE TITLE
Drawing sometimes doesn't work?

### ISSUE THREAD

**Issue by luskin** [RepairShopr/react-native-signature-capture#129]
This package is awesome, and works MOST of the time, however sometimes we open the view and there is just no touch handling what so ever... I'm not sure what really could be causing this but hopefully someone might be able to shed some light on the problem, thanks!

iOS 11
iPhone X Real Device + All iPhone Simulators

**Comment by SilverInfinity** [comment]
I have also run into this issue on iOS, haven't been able to recreate it on simulator, but multiple times on an actual iPhone X device. It appears to happen at random it seems, and when it does, the canvas has a hard thick black border around it, instead of the 1px border we've set in style. I wonder if this is related to #126 but unfortunately I don't know a lick of Objective-C to even begin to look into it. Here are the setting I'm currently using for signature capture: 
```jsx
<SignatureCapture
  style={styles.signature}
  ref="sign"
  onSaveEvent={this._onSaveEvent}
  onDragEvent={this._onDragEvent}
  saveImageFileInExtStorage
  showNativeButtons={false}
  showTitleLabel={false}
  viewMode={'portrait'}
/>
```
```javascript
styles = StyleSheet.create({
  signature: {
    borderColor: '#000033',
    borderWidth: 1,
    height: 320,
  },
}
```
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-signature-capture": "^0.4.9"

**Comment by luskin** [comment]
Thanks for posting #126 I'll see if I can reproduce

**Comment by luskin** [comment]
I have made more progress on the issue. It seems that the package does not work AT ALL when building for release. I have copy/pasted the example code from the repo, built the app in release and there is no touch handling for the signature field at all. The buttons of course work but there is no signature handling... not sure where to go from here.

**Comment by witalobenicio** [comment]
@luskin I tried your solution in iOS and it's not working. It shows the screen after didAppear, but I can't draw on it. You were able to solve it?

**Comment by witalobenicio** [comment]
@luskin nope...it's working, the problem was in my layout...it was not getting the full heigh and width.
